server:
  port: 9991

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_management_system
    username: postgres
    password: sadiq4852
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update